import 'token_parser.dart';

/// Base class for all token generators
abstract class BaseGenerator {
  BaseGenerator({
    required this.parser,
    this.onWarning,
    String? prefix,
  }) : prefix = prefix ?? 'Generated';

  final TokenParser parser;
  final void Function(String message)? onWarning;

  /// The prefix used for generated file names and class names.
  /// Defaults to 'Generated' if not specified.
  final String prefix;

  /// Generates Dart code from the tokens
  String generate(Map<String, dynamic> tokens);

  /// Returns the file name for the generated code (without prefix)
  String get baseFileName;

  /// Returns the class name for the generated code (without prefix)
  String get baseClassName;

  /// Returns the full file name with prefix
  /// For example: if prefix is 'MyDesign' and baseFileName is 'colors', returns 'my_design_colors.g.dart'
  String get fileName {
    final snakePrefix = _toSnakeCase(prefix);
    return '${snakePrefix}_$baseFileName.g.dart';
  }

  /// Returns the full class name with prefix
  /// For example: if prefix is 'MyDesign' and baseClassName is 'Colors', returns 'MyDesignColors'
  String get className => '$prefix$baseClassName';

  /// Converts a PascalCase or camelCase string to snake_case
  String _toSnakeCase(String input) {
    return input
        .replaceAllMapped(
          RegExp(r'([A-Z])'),
          (match) => '_${match.group(1)!.toLowerCase()}',
        )
        .replaceFirst(RegExp(r'^_'), '')
        .toLowerCase();
  }

  /// Generates the file header with imports and documentation
  String generateHeader({
    List<String> imports = const [],
    String? description,
  }) {
    final buffer = StringBuffer();

    buffer.writeln('// GENERATED CODE - DO NOT MODIFY BY HAND');
    buffer.writeln('// Generated by garmisch token generator');
    buffer.writeln('// Source: design-tokens.json');
    buffer.writeln();

    for (final import in imports) {
      buffer.writeln("import '$import';");
    }

    if (imports.isNotEmpty) {
      buffer.writeln();
    }

    if (description != null) {
      buffer.writeln('/// $description');
    }

    return buffer.toString();
  }

  /// Converts a token path to a valid Dart identifier
  ///
  /// For example: "gray.500" → "gray500", "xl-2" → "xl2"
  String toIdentifier(String path) {
    // Get the last part of the path
    final parts = path.split('.');
    final name = parts.last;

    // Remove invalid characters and convert to camelCase
    final cleaned = name
        .replaceAll(RegExp(r'[^a-zA-Z0-9]'), '')
        .replaceAllMapped(
          RegExp(r'^(\d)'),
          (m) => 'n${m.group(1)}',
        );

    return cleaned;
  }

  /// Converts a nested path to a flat identifier
  ///
  /// For example: "gray.500" → "gray500", "brand.primary" → "brandPrimary"
  String pathToIdentifier(String path) {
    final parts = path.split('.');
    if (parts.isEmpty) return '';

    final buffer = StringBuffer(toIdentifier(parts.first));
    for (var i = 1; i < parts.length; i++) {
      final part = toIdentifier(parts[i]);
      if (part.isNotEmpty) {
        // Capitalize first letter for camelCase
        buffer.write(part[0].toUpperCase() + part.substring(1));
      }
    }

    return buffer.toString();
  }

  /// Parses a dimension value (e.g., "16px") to a double
  double? parseDimension(dynamic value) {
    if (value is num) return value.toDouble();
    if (value is! String) {
      _warn('Invalid dimension value: $value');
      return null;
    }

    // Remove unit suffix
    final match = RegExp(r'^(-?[\d.]+)(px|rem|em|%)?$').firstMatch(value);
    if (match == null) {
      _warn('Invalid dimension format: $value');
      return null;
    }

    return double.tryParse(match.group(1)!);
  }

  /// Parses a duration value (e.g., "200ms") to milliseconds
  int? parseDuration(dynamic value) {
    if (value is int) return value;
    if (value is double) return value.toInt();
    if (value is! String) {
      _warn('Invalid duration value: $value');
      return null;
    }

    final match = RegExp(r'^(\d+)(ms|s)?$').firstMatch(value);
    if (match == null) {
      _warn('Invalid duration format: $value');
      return null;
    }

    final num = int.tryParse(match.group(1)!);
    if (num == null) return null;

    final unit = match.group(2) ?? 'ms';
    return unit == 's' ? num * 1000 : num;
  }

  /// Parses a color value (e.g., "#3B82F6") to a hex int
  int? parseColor(dynamic value) {
    if (value is! String) {
      _warn('Invalid color value: $value');
      return null;
    }

    String hex = value.trim();

    // Remove # prefix if present
    if (hex.startsWith('#')) {
      hex = hex.substring(1);
    }

    // Handle 6-digit hex (RGB) - add FF alpha
    if (hex.length == 6) {
      return int.tryParse('FF$hex', radix: 16);
    }

    // Handle 8-digit hex (ARGB)
    if (hex.length == 8) {
      return int.tryParse(hex, radix: 16);
    }

    _warn('Invalid color format: $value');
    return null;
  }

  void _warn(String message) {
    onWarning?.call(message);
  }
}

